### ISSUE TITLE
Edit BBT table is still very buggy

### ISSUE THREAD

**Issue by bbernhard1** [rocrail/Rocrail#18]
rev:8478

.) open BBT table -> edit intevall field -> "Apply" ->  "Apply"  => top line is cleared
.) open BBT table -> edit intevall field -> "Apply" ->  "OK"  => top line is cleared
.) open BBT table -> edit intevall field -> "Modify" ->  "OK"  => works ( a far as I remember)
 If we really need  "Modify" and "Apply" then please avoid that wrong seqeunce clear any data

**Comment by rocrail** [comment]
I confirm.
Next time please reopen the same issue to keep it clean.
