### ISSUE TITLE
Switch from long block symbol to short symbol swaps locomotive picture

### ISSUE THREAD

**Issue by bbernhard1** [rocrail/Rocrail#22]
see attached screenshots:

![unbenannt1](https://cloud.githubusercontent.com/assets/10500682/5889426/dc99e864-a425-11e4-8d69-ef0846ce97ed.PNG)
![unbenannt2](https://cloud.githubusercontent.com/assets/10500682/5889427/e1f57d50-a425-11e4-94a6-da82cfa90efb.PNG)

**Comment by rocrail** [comment]
You should update your SVG's because they have triangles on both sides.

**Comment by rocrail** [comment]
I cannot reproduce the issue.

**Comment by bbernhard1** [comment]
Hi Rob
I jsut found out that this happens only if block orientation is either "empty" or "west".  All other orientation work  do not show the swap.

**Comment by rocrail** [comment]
Why making an issue of this? How many times do you swap blocks between normal and small!?

**Comment by bbernhard1** [comment]
Am 26.01.2015 um 21:34 schrieb Rob Versluis:
>
> Why making an issue of this? How many times do you swap blocks between 
> normal and small!?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rocrail/Rocrail/issues/22#issuecomment-71532809>.
>

Why not make it perfect  ;-)
For sure, this is no big thing. Its definitly not necessary to spend big 
effort.

Ill give you an example how I recognized:

There are some blocks with long, and other blocks with short symbol in 
the layout.
I have all my loco pictures saved that they match with block orientation 
- to +.
So if you drag and drop you immediately know which direction the loco 
can drive.
Due to mixed behaviour of the blocks this was sometimes swaped and 
somehow confusing.
For myself Iam now ware about this, - no more problem.  But it might 
confuse others as well.

btw. I find very often minor issues like that. Do prefer to get them 
reported or better focus only on major issus?

br
bb


-- 
You can visit my family and me at
www.baptist-family.com

**Comment by rocrail** [comment]
Reporting issues is OK but follow the rules:
http://wiki.rocrail.net/doku.php?id=reporting-bug-en

**Comment by rocrail** [comment]
OK, I can reproduce it if I enable to show the loco image.
The arrow is right but the image is swapped.
