### ISSUE TITLE
RCP: Block updates do not remove reserved and entering attributes

### ISSUE THREAD

**Issue by moritzmhmk** [rocrail/Rocrail#23]
Using the Rocrail Client Protocol I found that updates on ``bk`` nodes do not clear the ``reserved`` and ``entering`` attributes. In my current implementation this leads to all blocks being reserved and entering after some time. (I read all attributes being send on an update and replace those in my plan).

I did expect the ``bk`` node to include ``reserved="false"`` and ``entering="false"`` when being updated.

I am not sure if this might be intended behavior - in this case I would like to know how the correct state of a block is to be determined :)

**Comment by rocrail** [comment]
This is not a bug; please use the forum

**Comment by moritzmhmk** [comment]
just to correct my issue: ``reserved="false"`` **is** being send - but ``entering="false"`` is not.

anyway thanks for the reply - I registered at the forum :)
