### ISSUE TITLE
"Save" is not working in Roc 

### ISSUE THREAD

**Issue by bbernhard1** [rocrail/Rocrail#26]
Hi, as in teh headline, "Save" seems to be broken in RocPro.
In general behaviour of the Save button is more like a toggle button, not as a push button.
Press once -> it become blue. Press second time it fades back to gray.

Furthermore the size of the RocPro window shoudl be extended. The left column is very thight, content cannot be read without expand the window.

**Comment by rocrail** [comment]
You should not report a bug before discussing it in the forum.
This report is your personal opinion.
