### ISSUE TITLE
DMX4ALL Interface: Missing channel offset

### ISSUE THREAD

**Issue by bahnwaerter** [rocrail/Rocrail#35]
I have tested the implementation and all works, except the addresses of the dmx channels. Some people will be confused, but the interface uses a channel offset:

E.g. set dmx channel 1:
#define CHANNEL_OFFSET 1
C[addr - CHANNEL_OFFSET]L[Value]

**Comment by rocrail** [comment]
OK, DMX4ALL is zero based.

**Comment by bahnwaerter** [comment]
Now, the DMX Interface is working fine. Also, the connection check with the N and I ASCII commands works without any problems. Great work, Rob, Thanks!
