### ISSUE TITLE
Request: Change Loco-CV via POM and action

### ISSUE THREAD

**Issue by micha68** [rocrail/Rocrail#40]

**Comment by rocrail** [comment]
Hi Micha,
can you provide some more information and a use case?

**Comment by micha68** [comment]
Hi Hob!
I would like to play with CV3 and CV4, especially in StagingBlocks.
I think it gives more scope than "Rangiergang".
Thanks, Michael

**Comment by micha68** [comment]
Danke Rob! Ich checke, sobald verfügbar!
